package com.example.contentprovider.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLightHighContrast = Color(0xFF04340B)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF265326)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF21301F)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF3D4D3B)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF003236)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF215055)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF7FBF1)
val onBackgroundLightHighContrast = Color(0xFF191D17)
val surfaceLightHighContrast = Color(0xFFF7FBF1)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDEE5D8)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF282E26)
val outlineVariantLightHighContrast = Color(0xFF444B42)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2D322C)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFA1D39A)
val surfaceDimLightHighContrast = Color(0xFFB6BAB2)
val surfaceBrightLightHighContrast = Color(0xFFF7FBF1)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEEF2E9)
val surfaceContainerLightHighContrast = Color(0xFFE0E4DB)
val surfaceContainerHighLightHighContrast = Color(0xFFD2D6CD)
val surfaceContainerHighestLightHighContrast = Color(0xFFC4C8BF)

val primaryDarkHighContrast = Color(0xFFC9FEC1)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF9DCF97)
val onPrimaryContainerDarkHighContrast = Color(0xFF000F01)
val secondaryDarkHighContrast = Color(0xFFE3F5DC)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB6C8B0)
val onSecondaryContainerDarkHighContrast = Color(0xFF030E03)
val tertiaryDarkHighContrast = Color(0xFFC9F8FE)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF9DCBD0)
val onTertiaryContainerDarkHighContrast = Color(0xFF000E10)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF10140F)
val onBackgroundDarkHighContrast = Color(0xFFE0E4DB)
val surfaceDarkHighContrast = Color(0xFF10140F)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF424940)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFECF2E6)
val outlineVariantDarkHighContrast = Color(0xFFBEC5B9)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE0E4DB)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF245125)
val surfaceDimDarkHighContrast = Color(0xFF10140F)
val surfaceBrightDarkHighContrast = Color(0xFF4D514B)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1C211B)
val surfaceContainerDarkHighContrast = Color(0xFF2D322C)
val surfaceContainerHighDarkHighContrast = Color(0xFF383D36)
val surfaceContainerHighestDarkHighContrast = Color(0xFF444841)







