package com.example.contentprovider.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLightHighContrast = Color(0xFF352C00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF564800)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF322C12)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF50492D)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF10321F)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF2E503A)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF9EE)
val onBackgroundLightHighContrast = Color(0xFF1E1B13)
val surfaceLightHighContrast = Color(0xFFFFF9EE)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEAE2D0)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2F2C20)
val outlineVariantLightHighContrast = Color(0xFF4D493B)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF333027)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFDBC66E)
val surfaceDimLightHighContrast = Color(0xFFBEB8AB)
val surfaceBrightLightHighContrast = Color(0xFFFFF9EE)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF7F0E2)
val surfaceContainerLightHighContrast = Color(0xFFE8E2D4)
val surfaceContainerHighLightHighContrast = Color(0xFFDAD4C6)
val surfaceContainerHighestLightHighContrast = Color(0xFFCCC6B9)

val primaryDarkHighContrast = Color(0xFFFFF0BA)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFD7C26B)
val onPrimaryContainerDarkHighContrast = Color(0xFF0F0B00)
val secondaryDarkHighContrast = Color(0xFFFCF0C9)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFCDC29E)
val onSecondaryContainerDarkHighContrast = Color(0xFF0F0B00)
val tertiaryDarkHighContrast = Color(0xFFD2FADB)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFA5CCAF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000F05)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF15130B)
val onBackgroundDarkHighContrast = Color(0xFFE8E2D4)
val surfaceDarkHighContrast = Color(0xFF15130B)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4B4739)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF7EFDD)
val outlineVariantDarkHighContrast = Color(0xFFC9C2B1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE8E2D4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF554700)
val surfaceDimDarkHighContrast = Color(0xFF15130B)
val surfaceBrightDarkHighContrast = Color(0xFF535046)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF222017)
val surfaceContainerDarkHighContrast = Color(0xFF333027)
val surfaceContainerHighDarkHighContrast = Color(0xFF3E3B32)
val surfaceContainerHighestDarkHighContrast = Color(0xFF4A473D)







